import React from 'react'
import { makeStyles } from '@material-ui/core/styles';
import AppBar from '@material-ui/core/AppBar';
import CssBaseline from '@material-ui/core/CssBaseline';
import EEM from "../img/tamogatok/EEM.png";
import EKMK from "../img/tamogatok/EKMK.png";
import magyarfaluprogramlogo from "../img/tamogatok/magyarfaluprogramlogo.png";
import nka from "../img/tamogatok/nka.png";
import NMI from "../img/tamogatok/nmi.png";
import SMBleader from "../img/tamogatok/SMBleader.jpg";

const messages = [
    {
        id: 1,
        primary: 'Brunch this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 2,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/avatar/1.jpg',
    },
    {
        id: 3,
        primary: 'Recipe to try',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/avatar/2.jpg',
    },
    {
        id: 4,
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/avatar/3.jpg',
    },
    {
        id: 5,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
    },
    {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
    },
];

const useStyles = makeStyles((theme) => ({
    appBar: {
        position:"relative",
        display: "flex",
        height: "170px",
        justifyContent: "space-between",
        backgroundColor: "rgba(0, 0, 0, 0.0)",
        alignItems: "center"
    },
    logoContainer: {
        top: 'auto',
        bottom: 0,
        display: "flex",
        height: "80px",
        justifyContent: "space-between",
        alignItems: "center"
    },
    img: {
        height: "7.5vh",
        margin: "6px",
        borderRadius: "1px",
    }


}));

const Footer = () => {
    const classes = useStyles();
    return (
        <React.Fragment>
            <CssBaseline />
            <AppBar position="fixed" color="primary" className={classes.appBar}>
                <div className={classes.logoContainer}>
                    <img className={classes.img} src={EKMK} alt="Veszprém EKMK" />
                    <img className={classes.img} src={nka} alt="Nemzeti Kulturális Alap" />
                    <img  style={{background:"#185230"}} className={classes.img} src={NMI} alt="Emberi Erőforrások Minisztériuma" />
                </div>
                <div className={classes.logoContainer}>
                    <img className={classes.img} src={EEM} alt="Emberi Erőforrások Minisztériuma" />
                    <img className={classes.img} src={magyarfaluprogramlogo} alt="Emberi Erőforrások Minisztériuma" />
                    <img className={classes.img} src={SMBleader} alt="Emberi Erőforrások Minisztériuma" />
                </div>

            </AppBar>
        </React.Fragment>
    )
}

export default Footer
